version: "3.7"

services:
  subscriber_mqtt_1:
    container_name: subscriber_mqtt_1
#    image: golfvert/wis2globalbrokernodered
#    image: docker.io/library/testing:WIS2-GlobalBrokerAntiLoop
    image: docker.io/library/testing:node-red-build
    env_file:
      - ./publisher.env
    environment:
      - TZ=Europe/Paris
      - MQTT_SUB_HOST=Broker_IPAddr   # WIS2Node broker
      - MQTT_SUB_PORT=Broker_Port
      - MQTT_SUB_USER=
      - MQTT_SUB_PASSWD=
      - MQTT_SUB_TOPIC=Topic_to_sub   # e.g. wis/a/origin/FRA/#
    ports:
      - "1880:1880"
    networks:
      - wis2relay
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --save 20 1
    ports:
      - "6379:6379"
    networks:
      - wis2relay
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Redis:/data
networks:
  wis2relay:
    driver: bridge
